Fix workflow join clause

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -90,6 +90,14 @@ jobs:
       - lint
       - unit-tests
       - integration-tests
+    if: '!cancelled()'
     steps:
       - name: Done
+        if: needs.lint.result == 'success' && needs.unit-tests.result == 'success' && needs.integration-tests.result == 'success'
         run: echo "OK"
+      - name: Done
+        if: needs.lint.result != 'success' || needs.unit-tests.result != 'success' || needs.integration-tests.result != 'success'
+        run: |-
+          echo "Failed!"
+          exit 1
+
