Move coverage to dedicated job

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -317,18 +317,35 @@ jobs:
       - integration-tests
     if: '!cancelled()'
     steps:
+      - name: Success
+        if: needs.generate.result == 'success' && needs.lint.result == 'success' && needs.lint-workflows.result == 'success' && needs.unit-tests.result == 'success' && needs.integration-tests.result == 'success'
+        run: echo "OK"
+      - name: Failed
+        if: needs.generate.result != 'success' || needs.lint.result != 'success' || needs.lint-workflows.result != 'success' || needs.unit-tests.result != 'success' || needs.integration-tests.result != 'success'
+        run: |-
+          echo "Failed!"
+          exit 1
+
+  ##############################################################################
+  # Produce a CodeCov coverage report with all uploaded code coverage data.
+  coverage-report:
+    runs-on: ubuntu-latest
+    name: Coverage Report
+    needs:
+      - generate
+      - unit-tests
+      - integration-tests
+    if: github.event_name != 'merge_group'
+    steps:
       - name: Checkout
-        if: github.event_name != 'merge_group'
         uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
       - name: Download coverage reports
-        if: github.event_name != 'merge_group'
         uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
         with:
           merge-multiple: false # Extract in per-artifact directories
           pattern: coverage-reports.*
           path: coverage
       - name: Download codecov CLI
-        if: github.event_name != 'merge_group'
         run: |-
           set -euo pipefail
 
@@ -348,7 +365,6 @@ jobs:
           BASE_URL: https://cli.codecov.io/latest/linux${{ runner.arch == 'ARM64' && '-arm64' || '' }}/codecov
         working-directory: ${{ runner.temp }}
       - name: Submit coverage data to CodeCov
-        if: github.event_name != 'merge_group' && needs.generate.result == 'success' && needs.unit-tests.result == 'success' && needs.integration-tests.result == 'success'
         shell: bash
         run: |-
           pr=()
@@ -440,12 +456,3 @@ jobs:
           echo "::endgroup::"
         env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
-      - name: Success
-        if: needs.generate.result == 'success' && needs.lint.result == 'success' && needs.lint-workflows.result == 'success' && needs.unit-tests.result == 'success' && needs.integration-tests.result == 'success'
-        run: echo "OK"
-      - name: Failed
-        if: needs.generate.result != 'success' || needs.lint.result != 'success' || needs.lint-workflows.result != 'success' || needs.unit-tests.result != 'success' || needs.integration-tests.result != 'success'
-        run: |-
-          echo "Failed!"
-          exit 1
-
